# This file contains all the "targets" cross can be used with by default and is used for generating `src/docker/provided_images.rs` and our images
# the only required value for a `target` entry is its name in `target.target` and the `os` to use in CI
#
# spec is available in `xtask/src/util.rs` on `CiTarget`

[[target]]
target = "x86_64-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"
deploy = true

[[target]]
target = "i686-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"
deploy = true

[[target]]
target = "aarch64-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "armv7-unknown-linux-gnueabihf"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "mipsel-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"
build-std = true

[[target]]
target = "mips64el-unknown-linux-gnuabi64"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"
build-std = true

[[target]]
target = "powerpc-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "powerpc64-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "powerpc64le-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "riscv64gc-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "s390x-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-system"

[[target]]
target = "cross"
os = "ubuntu-latest"
special = true
