FROM debian:bookworm AS common

ARG CROSS_TARGET=armv7-unknown-linux-gnueabihf
ENV DEBIAN_FRONTEND=noninteractive
ENV CROSS_TOOLCHAIN_PREFIX=arm-linux-gnueabihf-
ENV CROSS_SYSROOT=/usr/arm-linux-gnueabihf

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    g++-arm-linux-gnueabihf \
    gfortran-arm-linux-gnueabihf \
    libc6-dev-armhf-cross

COPY deny-debian-packages.sh /
RUN TARGET_ARCH=armhf /deny-debian-packages.sh \
    binutils \
    binutils-arm-linux-gnueabihf

FROM common AS valgrind

ARG VALGRIND_VERSION=3.27.0
ARG VALGRIND_CONFIGURE_ARGS="--prefix=/usr --enable-tls --enable-lto --enable-only32bit"
ARG VALGRIND_CONFIGURE_EXTRA_ARGS=""
ARG VALGRIND_MAKE_EXTRA_ARGS=""

COPY valgrind.sh /
RUN /valgrind.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common as dropbear

ARG DROPBEAR_VERSION=2025.88

COPY dropbear.sh dropbear_options.h /
RUN /dropbear.sh armhf

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common as util-linux

ARG UTIL_LINUX_VERSION=2.41.2

COPY util-linux.sh /
RUN /util-linux.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common as image

COPY --from=valgrind /valgrind /tmp/valgrind/
COPY --from=util-linux /util-linux/usr/bin/setarch /tmp/util-linux/
COPY --from=dropbear /dropbear /tmp/dropbear/
COPY --from=dropbear /usr/bin/dropbearkey /usr/bin/

COPY linux-image.sh /
RUN /linux-image.sh armv7

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common as qemu

COPY --from=valgrind /valgrind/usr/include/valgrind /usr/include/valgrind/

ARG SLIRP_VERSION=4.9.1
ARG QEMU_VERSION=10.0.4

COPY slirp.sh /
RUN /slirp.sh

# slirp installs the pkg-config files here
ENV PKG_CONFIG_PATH=/usr/lib64/pkgconfig

COPY qemu.sh /
RUN /qemu.sh arm

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common as runner

COPY --from=dropbear /usr/bin/dbclient \
    /usr/bin/dropbearkey \
    /usr/bin/scp \
    /usr/bin/
COPY --from=image /qemu /qemu/
COPY --from=qemu /qemu /
COPY --from=qemu /usr/lib64/libslirp.so.0.4.0 /usr/lib64/
COPY --from=valgrind /valgrind/usr/include/valgrind /usr/include/valgrind/

RUN cd /usr/lib/ && \
    ln -s /usr/lib64/libslirp.so.0.4.0 . && \
    ln -s libslirp.so.0.4.0 libslirp.so.0 && \
    ln -s libslirp.so.0 libslirp.so

COPY linux-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TARGET_RUNNER="/linux-runner armv7hf"
ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_armv7_unknown_linux_gnueabihf="${CROSS_TOOLCHAIN_PREFIX}ar" \
    CC_armv7_unknown_linux_gnueabihf="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CXX_armv7_unknown_linux_gnueabihf="${CROSS_TOOLCHAIN_PREFIX}g++" \
    CMAKE_TOOLCHAIN_FILE_armv7_unknown_linux_gnueabihf=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_armv7_unknown_linux_gnueabihf="--sysroot=$CROSS_SYSROOT -idirafter/usr/include" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}" \
    PKG_CONFIG_ALLOW_CROSS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=arm \
    CROSS_CMAKE_CRT=gnu \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -march=armv7-a -mfpu=vfpv3-d16"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /linux-runner
