FROM debian:bookworm AS common

ARG CROSS_TARGET=i686-unknown-linux-gnu
ENV DEBIAN_FRONTEND=noninteractive
ENV CROSS_TOOLCHAIN_PREFIX=i686-linux-gnu-
ENV CROSS_SYSROOT=/usr/i686-linux-gnu

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    g++-i686-linux-gnu \
    gfortran-i686-linux-gnu \
    libc6-dev-i386-cross

COPY deny-debian-packages.sh /
RUN TARGET_ARCH=i386 /deny-debian-packages.sh \
    binutils \
    binutils-i686-linux-gnu

FROM common AS valgrind

ARG VALGRIND_VERSION=3.27.0
ARG VALGRIND_CONFIGURE_ARGS="--prefix=/usr --enable-tls --enable-lto --enable-only32bit"
ARG VALGRIND_CONFIGURE_EXTRA_ARGS=""
ARG VALGRIND_MAKE_EXTRA_ARGS=""

COPY valgrind.sh /
RUN /valgrind.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS dropbear

ARG DROPBEAR_VERSION=2025.88

COPY dropbear.sh dropbear_options.h /
RUN /dropbear.sh i386

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS util-linux

ARG UTIL_LINUX_VERSION=2.41.2

COPY util-linux.sh /
RUN /util-linux.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS image

COPY --from=valgrind /valgrind /tmp/valgrind/
COPY --from=util-linux /util-linux/usr/bin/setarch /tmp/util-linux/
COPY --from=dropbear /dropbear /tmp/dropbear/
COPY --from=dropbear /usr/bin/dropbearkey /usr/bin/

COPY linux-image.sh /
RUN /linux-image.sh i686

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS qemu

COPY --from=valgrind /valgrind/usr/include/valgrind /usr/include/valgrind/

ARG SLIRP_VERSION=4.9.1
ARG QEMU_VERSION=10.0.4

COPY slirp.sh /
RUN /slirp.sh

# slirp installs the pkg-config files here
ENV PKG_CONFIG_PATH=/usr/lib64/pkgconfig

COPY qemu.sh /
RUN /qemu.sh i386

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS runner

COPY --from=dropbear /usr/bin/dbclient \
    /usr/bin/dropbearkey \
    /usr/bin/scp \
    /usr/bin/
COPY --from=image /qemu /qemu/
COPY --from=qemu /qemu /
COPY --from=qemu /usr/lib64/libslirp.so.0.4.0 /usr/lib64/
COPY --from=valgrind /valgrind/usr/include/valgrind /usr/include/valgrind/

RUN cd /usr/lib/ && \
    ln -s /usr/lib64/libslirp.so.0.4.0 . && \
    ln -s libslirp.so.0.4.0 libslirp.so.0 && \
    ln -s libslirp.so.0 libslirp.so

COPY linux-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TARGET_RUNNER="/linux-runner i686"
ENV CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_i686_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}ar" \
    CC_i686_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CXX_i686_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}g++" \
    CMAKE_TOOLCHAIN_FILE_i686_unknown_linux_gnu=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_i686_unknown_linux_gnu="--sysroot=$CROSS_SYSROOT -idirafter/usr/include" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/i386-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}" \
    PKG_CONFIG_ALLOW_CROSS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86 \
    CROSS_CMAKE_CRT=gnu \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m32 -march=i686"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /linux-runner
