FROM debian:bookworm-20260505 AS common

ARG CROSS_TARGET=x86_64-unknown-linux-gnu
ENV DEBIAN_FRONTEND=noninteractive
ENV CROSS_TOOLCHAIN_PREFIX=x86_64-linux-gnu-
ENV CROSS_SYSROOT=/usr/x86_64-linux-gnu

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    g++-x86-64-linux-gnu \
    gfortran \
    libc6-dev-amd64-cross \
    && rm -rf /usr/share/doc /usr/share/info /usr/share/locale /usr/share/man /usr/share/gtk-doc /var/lib/apt/lists/*

COPY deny-debian-packages.sh /
RUN TARGET_ARCH=amd64 /deny-debian-packages.sh \
    binutils \
    binutils-x86-64-linux-gnu

FROM common AS packages

ARG CROSS_TARGET=x86_64-unknown-linux-gnu
COPY packages.sh lib.sh /
RUN /packages.sh x86_64

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS valgrind

ARG VALGRIND_VERSION=3.27.0
ARG VALGRIND_CONFIGURE_ARGS="--prefix=/opt/valgrind --enable-tls --enable-lto --enable-only64bit"
ARG VALGRIND_CONFIGURE_EXTRA_ARGS=""
ARG VALGRIND_MAKE_EXTRA_ARGS=""
ARG VALGRIND_CFLAGS=""

COPY valgrind.sh /
RUN /valgrind.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS zlib

ARG ZLIB_VERSION=1.3.2

COPY zlib.sh /
RUN /zlib.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS dropbear

COPY --from=zlib /zlib /tmp/zlib/
COPY --from=packages /packages/libcrypt-dev* /tmp/packages/

ARG DROPBEAR_VERSION=2025.88

COPY dropbear.sh dropbear_options.h /
RUN /dropbear.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS util-linux

ARG UTIL_LINUX_VERSION=2.41.2

COPY util-linux.sh /
RUN /util-linux.sh

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS image

COPY --from=packages /packages/busybox* \
    /packages/libc6* \
    /packages/libcrypt1* \
    /packages/libgcc* \
    /packages/libgmp10* \
    /packages/libstdc++6* \
    /packages/libtomcrypt1* \
    /packages/libtommath1* \
    /packages/linux-* \
    /packages/ncurses-base* \
    /tmp/packages/
COPY --from=util-linux /util-linux/usr/bin/setarch /tmp/util-linux/
COPY --from=dropbear /dropbear /tmp/dropbear/
COPY --from=dropbear /usr/bin/dropbearkey /usr/bin/

COPY linux-image.sh /
RUN /linux-image.sh x86_64

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS qemu

COPY --from=valgrind /valgrind/opt/valgrind/include/valgrind /usr/include/valgrind/

ARG SLIRP_VERSION=4.9.1
ARG QEMU_VERSION=10.0.4

COPY slirp.sh /
RUN /slirp.sh

# slirp installs the pkg-config files here
ENV PKG_CONFIG_PATH=/usr/lib64/pkgconfig

COPY qemu.sh /
RUN /qemu.sh x86_64

RUN apt-get autopurge -y \
    && rm -rf /var/lib/apt/lists/*

FROM common AS runner

COPY --from=dropbear /usr/bin/dbclient \
    /usr/bin/dropbearkey \
    /usr/bin/scp \
    /usr/bin/
COPY --from=image /qemu /qemu/
COPY --from=qemu /qemu /
COPY --from=qemu /usr/lib64/libslirp.so.0.4.0 /usr/lib64/
COPY --from=valgrind /valgrind/opt/valgrind/include/valgrind /usr/include/valgrind/
COPY --from=valgrind /valgrind /

RUN cd /usr/lib/ && \
    ln -s /usr/lib64/libslirp.so.0.4.0 . && \
    ln -s libslirp.so.0.4.0 libslirp.so.0 && \
    ln -s libslirp.so.0 libslirp.so

COPY linux-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TARGET_RUNNER="/linux-runner x86_64"
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_x86_64_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}ar" \
    CC_x86_64_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}gcc" \
    CXX_x86_64_unknown_linux_gnu="${CROSS_TOOLCHAIN_PREFIX}g++" \
    CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu="--sysroot=$CROSS_SYSROOT -idirafter/usr/include" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}" \
    PKG_CONFIG_ALLOW_CROSS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=gnu \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /linux-runner
