#!/usr/bin/env bash

set -e

# shellcheck disable=SC1091
. /base-runner.sh

# Return true if the log level is debug
is_debug() {
    [[ -n "$CROSS_DEBUG" ]]
}

# If debugging is activated, execute the given arguments in a subshell
if_debug() {
    if is_debug; then
        "$@"
    else
        true
    fi
}

# If debugging is not set, execute the given arguments in a subshell
if_not_debug() {
    if ! is_debug; then
        "$@"
    else
        true
    fi
}

if_debug set -x

LOG=/tmp/qemu.log
LOCK=/tmp/qemu.lock

# arch in the rust target
arch="${1}"
shift

if [[ -z "${CROSS_RUNNER}" ]]; then
    if is_native_binary "${arch}"; then
        CROSS_RUNNER=native
    else
        CROSS_RUNNER=qemu-user
    fi
fi

# Ensure that the correct prefix is set even if the user has cleared the env.
# `@DEFAULT_QEMU_LD_PREFIX@` is replaced during image build.
export QEMU_LD_PREFIX=${QEMU_LD_PREFIX:-@DEFAULT_QEMU_LD_PREFIX@}

echo -n "linux-runner: args: "
echo "${@}"

qarch=$(qemu_arch "${arch}")
case "$qarch" in
ppc64le)
    qarch=ppc64
    ;;
*) ;;
esac

case "${CROSS_RUNNER}" in
native)
    exec "${@}"
    ;;
qemu-user)
    exec "qemu-${qarch}" "${@}"
    ;;
qemu-system)
    true
    ;;
*)
    echo "Invalid runner: \"${CROSS_RUNNER}\""
    echo "Valid runners are: qemu-system"
    exit 1
    ;;
esac

n="$(nproc)"
memory=1G
driver9p="virtio-9p-pci"
drivernet="virtio-net-pci"

# select qemu parameters
case "${arch}" in
aarch64 | aarch64_be)
    # 8 is the max number of cpu supported by qemu-aarch64
    n=$((n > 8 ? 8 : n))
    opt="-machine virt -cpu cortex-a57"
    ;;
armv7hf)
    opt="-machine virt"
    driver9p="virtio-9p-device"
    drivernet="virtio-net-device"
    ;;
i686)
    opt="-append console=ttyS0"
    ;;
mips | mipsel)
    opt="-append nokaslr"
    n=1
    ;;
mips64el)
    opt="-append nokaslr -M malta -cpu MIPS64R2-generic"
    n=1
    ;;
powerpc)
    opt="-append console=ttyPZ0"
    n=1
    ;;
riscv64)
    opt="-machine virt"
    ;;
powerpc64 | powerpc64le)
    opt="-append console=hvc0 --nodefaults -serial stdio"
    ;;
s390x)
    n=1
    driver9p="virtio-9p-ccw"
    drivernet="virtio-net-ccw"
    ;;
x86_64)
    opt="-append console=ttyS0"
    ;;
esac

(
    flock -n 200 || exit 0

    echo Booting QEMU virtual machine with "$n" cpus...

    QEMU_CMD="qemu-system-${qarch} \
        -m ${memory} \
        -smp ${n} \
        -nographic \
        -monitor none \
        -nic user,model=${drivernet},hostfwd=tcp::10022-:22,ipv6=off \
        -kernel /qemu/kernel \
        -initrd /qemu/initrd.gz \
        ${opt} \
        -fsdev local,id=fs0,path=/target,security_model=mapped \
        -device ${driver9p},fsdev=fs0,mount_tag=target"

    touch "${LOG}"
    if is_debug; then
        # Close fd 200 in child so it doesn't hold the flock lock
        (
            exec 200>&-
            ${QEMU_CMD} 2>&1 | tee -a "${LOG}"
        ) &
    else
        (
            exec 200>&-
            ${QEMU_CMD} >>"${LOG}" 2>&1
        ) &
    fi
    qemu_pid=$!

    # Wait for qemu to print dropbear's final 'Not backgrounding' message or until
    # the timeout is reached
    ticks=0
    timeout=240
    while true; do
        if ! kill -0 "$qemu_pid" 2>/dev/null; then

            echo -e "\nStarting qemu failed:\n"
            if_not_debug echo "Set the environment variable CROSS_DEBUG=1 to debug"
            if_not_debug echo "Last 100 lines of qemu output:"
            if_not_debug tail -n 100 "${LOG}"

            exit 1
        elif tail -10 "$LOG" | grep -q -e '---\[ end Kernel panic'; then
            kill -9 $qemu_pid

            echo -e "\nStarting qemu failed:\n"
            if_not_debug echo "Set the environment variable CROSS_DEBUG=1 to debug"
            if_not_debug echo "Last 100 lines of qemu output:"
            if_not_debug tail -n 100 "${LOG}"

            exit 1
        elif tail -10 "$LOG" | grep -q "Not backgrounding"; then
            break
        elif ((ticks >= timeout)); then
            kill -9 $qemu_pid

            echo "Qemu is not ready after ${ticks} seconds..."

            if_not_debug echo "Set the environment variable CROSS_DEBUG=1 to debug"
            if_not_debug echo "Last 100 lines of qemu output:"
            if_not_debug tail -n 100 "${LOG}"

            exit 1
        else
            : # do nothing
        fi

        sleep 0.5
        _=$((ticks++))
    done

    echo "Booted in $((ticks / 2)) seconds"

) 200>"${LOCK}"

if [[ -t 1 ]] && [[ -t 2 ]]; then
    tty_flag='-t'
else
    tty_flag='-T'
fi

if [[ -n "${CROSS_VALGRIND}" || -n "$*" ]]; then
    # shellcheck disable=2086
    exec dbclient "${tty_flag}" -p 10022 -y -y root@localhost ${CROSS_VALGRIND} "${@}"
fi
