on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:
    inputs:
      targets:
        required: false
        description: 'check these space or comma separated targets, supports wildcard *'

name: Check

env:
  CARGO_NET_RETRY: 3
  CARGO_HTTP_CHECK_REVOKE: false

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: EmbarkStudios/cargo-deny-action@v2
